### ISSUE TITLE
Documentation in Readme is out of date

### ISSUE THREAD

**Issue by ichttt** [ben-xo/vu2#1]
Readme states that button pin is D4 by default, but in the latest version it is D7.
Also, I can't figure out how to adjust the sensitivity in sampler.cpp (as outlined by the readme).
It would also be helpful if you could tell which arduino you have been using for this. I have a feeling that my uno has not enough power to handle all the computations in (can't test though since I don't have an oscilloscope).
Cause this looks like a awesome project if I could get it to work properly

**Comment by ben-xo** [comment]
Hi There! I'm so sorry I only just saw this. You're the first person to ask!! 

I'll see what I can do with the doc, and give you some guidance - feel free to contact me more directly (@benxo on Twitter or ben-xo on Reddit if you want) or we can discuss here - but I seem to miss notifications a lot here!

**Comment by ben-xo** [comment]
I am using an Arduino Nano (16MHz AVR) - it won't work with a non-AVR Arduino because this is very much a project i've done for myself, not that it should be hard to get working, and i'd love to help you out.

**Comment by ben-xo** [comment]
Hopefully #2 will help a bit? Can also share some pictures if you like>

**Comment by ichttt** [comment]
Hi, yeah I've kinda given up on using beat detection and just build some other cool effects with my neostrip. But thanks anyway!
The documentation improvements look good, hopefully it well help some future persons that are trying to build something like this.
